### ISSUE TITLE
Team is not shown on the Kickoff Submission Form

### ISSUE THREAD

**Issue by maximiliansoelch** [ls1intum/prompt#123]
If I create a team and then go to the team submission form, I do not see the team listed there.

Also, this form includes fields that should not be there, like Apple ID, Device ID, etc.

![image](https://github.com/ls1intum/prompt/assets/9954674/6bb303fc-45e8-4f53-811a-0eeb57b7442d)

**Comment by maximiliansoelch** [comment]
This is the error when accessing the form:

![image](https://github.com/ls1intum/prompt/assets/9954674/71f97b2c-fd81-4998-bd59-14cafb89db86)

**Comment by airelawaleria** [comment]
solved in the latest deployment :)
