### ISSUE TITLE
Error: Invalid value for <svg> attribute width="2.25rem"

### ISSUE THREAD

**Issue by Erik262** [ls1intum/prompt#22]
I want to report an issue that is only visible through the console.
Steps to do: Nothing
![27-06-2023 at 22-53-48](https://github.com/ls1intum/prompt/assets/11977647/e58703e0-6c4d-4b08-af16-a41e176d0709)

**Comment by airelawaleria** [comment]
Hmm, cannot reproduce the issue. Might be a problem with your browser? Which one do you use and which exact version?

**Comment by Erik262** [comment]
@airelawaleria 
I'm using Safari 16.5.1 on macOS Ventura 13.4.1
No add blocker VPN etc is on.
 Issue still preserves:
![28-06-2023 at 18-12-28](https://github.com/ls1intum/prompt/assets/11977647/0e22920a-d0b7-4d65-b4c4-01f3708b78c3)
