### ISSUE TITLE
[Student Applications] "Additional Notes" are not fetched when closing and reopening an application

### ISSUE THREAD

**Issue by bgeisb** [ls1intum/prompt#251]
## Steps to Reproduce

1. Go to the student applications section.
2. Open any student application.
3. Enter some text into the "Additional Notes" field.
4. Press "Send" and close the application.
5. Reopen the same application.
6. Navigate to the "Additional Notes" section.

## Expected Behavior
When reopening the application, the "Additional Notes" that were previously entered and saved should be fetched and displayed correctly in the text field. Users should be able to view or add more notes as needed.

## Actual Behavior
Upon reopening the application, the "Additional Notes" section is empty or does not display the notes that were saved during the previous session. This suggests that the notes are either not being fetched correctly from the database or there is an issue with displaying them in the UI.

**Comment by airelawaleria** [comment]
It fixed with the latest deployment

**Comment by airelawaleria** [comment]
It is fixed with the latest deployment.
